- botcity/web/bot.py
FIXED: If two matches were next to each other, but without at least a pixel separating them, the bot would consider them to be duplicates.
> Fixed minor bug in find_all()

- botcity/web/bot.py
Optionally allows the find_all method to return a list with the found elements instead of a generator.
Pending:
(Docs): Returns should be changed to reflect the new return possibility?
> Added find_all(as_list=True) + set_current_element

- botcity/web/browsers/chrome.py
**Problem:** Chrome does not save automatically when printing page as pdf.
**Solution** 
```python
app_state = {
'recentDestinations': [{
'id': 'Save as PDF',
'origin': 'local',
'account': ''   # added
}],
'selectedDestinationId': 'Save as PDF',
'version': 2
}
````
> FIX: added 'account' key on recentDestinations

- botcity/web/bot.py
When `set_screen_resolution(width, height)` is called doesn't update `self._dimensions` attribute.
```python
from botcity.web import WebBot, Browser
web = WebBot()
web.headless = False
web.browser = Browser.FIREFOX
web.driver_path = '<path>'
web.browse('https://www.google.com')
web.set_screen_resolution(1280, 720)
print(web.display_size())  # (1600, 900)
```
> FIX: _dimensions value assignment

- botcity/web/bot.py
Checking the `*.part` file exists when is downloading on Firefox.
> FIX: Checking if the file has been downloaded completely on Firefox

- botcity/web/bot.py
`@only_if_element` raises an error because `self.state.element` is `None`.
`self.click(x, y)` doesn't have `x`, `y` params.
```python
@only_if_element
def click_on(self, label):
"""
Click on the element.
Args:
label (str): The image identifier
"""
x, y = self.get_element_coords_centered(label)
self.click(x, y)
```
> FIX: 'click_on()' method

- botcity/web/bot.py
- botcity/web/browsers/chrome.py
- botcity/web/browsers/edge.py
Added changes:
- New key in "prefs" dict in Chrome and Edge, to automatically download pdf files instead of opening a page with pdf viewer.
- Added **check_file_count** method to count the amount of files of a certain type in a folder.
- Added **wait_for_new_pdf** method to wait for the pdf file to be saved in the folder, when you don't have the exact file path.
- Added **return_last_created_file** method to return the last file that was created/downloaded in a folder.
- Changes in the **print_pdf** method to save the files in the correct path, using the new methods created. 
Closes #20
> BUG: fix related to saving files in print_pdf method - Issue #20

- botcity/web/bot.py
Updates:
- Implemented a handling to wait for all files to be downloaded when using Chrome or Edge in headless mode. In this solution, files of type `.crdownload` are handled as an alternative to the Javascript code that is used to control downloads in headfull mode. 
fixes #30
> BUG: updated wait_for_downloads method when headless

- botcity/web/bot.py
- botcity/web/browsers/chrome.py
- botcity/web/browsers/edge.py
Updates:
- Removed `--disable-extensions` argument to add extensions in Chrome and Edge.
- Implemented `install_firefox_extension` method to install Firefox extensions through Selenium's `install_addon` command.
> ENH: added support to be able to use extensions in browsers

- botcity/web/bot.py
Closes #30 
Due to the nature of WebBot, we can't pickle the screenshot image therefore it causes the error reported when trying to pickle the Image. Switching back to the simple method to find multiple entries. No significant performance penalty.
> FIX: Remove multiprocessing from find_multiple due to pickling issues.

- botcity/web/bot.py
Updated:
- Added a sleep before the return statement on `wait_for_file` and `wait_for_new_file` methods, to prevent the file from being accessed without being completely saved and released.
fixes #39
> BUG: inserted sleep before returning from wait_for_file method

- botcity/web/browsers/chrome.py
- botcity/web/browsers/edge.py
Came across the need for this flag when testing the Docker containers.
> FIX: Add --no-sandbox if running Chrome and Edge as root.

- botcity/web/browsers/edge.py
- docs-requirements.txt
Sometimes the webbot runs javascript before loading the download page.
> FIX: Added wait after going to downloads page

- botcity/web/bot.py
This method is useful to scroll down a HTML element in cases where more child elements are loaded as the page is scrolled.
Examples include:
- LinkedIn search list
- Most product pages on modern websites
- Facebook infinity scroll
- Instagram posts
- etc...
> ENH: Add scroll_element method.

- botcity/web/parsers.py
Allow users to specify a custom XPath for the table cell elements for situations in which `th` is mixed with `td` on rows.
Here is a real use case from the [Nasdaq Screener](https://www.nasdaq.com/market-activity/stocks/screener) table:
```python
screener_table = self.find_element(selector="nasdaq-screener__table", by=By.CLASS_NAME)
data = table_to_dict(
table=screener_table,
has_header=True,
cell_xpath="//*[contains(@class,'nasdaq-screener__cell')]"
)
```
> ENH: Improve table to dict parser to accept custom XPath for table cell.

- botcity/web/bot.py
Replacing the title characters (|\/:–) so that it is possible to save the pdf in the Firefox browser.
> Replacing title characters

- .github/workflows/ci.yml
This PR does the following:
- Expands the matrix to include Windows and macOS
- Fix the `if` statement to avoid installing the browsers when not required
- Disable `fail-fast` so we can follow the other test scenarios from the matrix even if one fails
Tested on my fork and everything is running ok. The `download` test is a bit flaky and we should look into it once we have an opportunity.
> CI: Expand matrix to include Windows and macOS.

- .github/workflows/ci.yml
- conftest.py
- tests/test_browser.py
- tests/test_keyboard.py
- tests/test_mouse.py
- tests/test_vision.py
Base test functions for keyboard, mouse, and computer vision using the browser exclusively.
> TST: Expand tests to keyboard, mouse and vision

- botcity/web/bot.py
- tests/test_browser.py
Simple implementation of a context for executing the web browser.
The proposal is to facilitate the execution and closing of the browser by context, avoiding treatments by users with finally clauses or forgetting to close browsers.
Exemplification of use in the test "test_context".
> ENH: Implement __enter__ and __exit__ to open and stop browser

- botcity/web/bot.py
- botcity/web/browsers/chrome.py
- botcity/web/browsers/edge.py
- botcity/web/browsers/firefox.py
- botcity/web/browsers/undetected_chrome.py
- conftest.py
Now you can pass the location of the binary you want to run.
This opens up possibilities:
- Run any Chrome-based Browser (Brave, Vivaldi, OperaGX, Chrome Beta, etc.)
- Run any Firefox Based Browser (Tor, LibreWolf, Firefox Beta)
(Warning: Tor needs some additional settings to connect to Tor Network first)
- Run browsers in different versions without modifying the default Browser that is in the OS.
> ENH: Implement binary path

- README.md
> DOC: Updating screenshots and links in README

- botcity/web/browsers/undetected_chrome.py
- requirements.txt
More details here: https://www.selenium.dev/blog/2023/headless-is-going-away/
> FIX: Deprecate headless option under ChromeOptions to comply with Selenium >=4.10.

- .github/workflows/ci.yml
Macos-latest issue related to ARM architecture in Firefox and edge.
- https://github.com/browser-actions/setup-edge/issues/481
- https://github.com/browser-actions/setup-firefox/issues/545
> CI: Remove macos-latest
